version: "3.6"
services:
  web:
    build: web
    image: corentingarreau/pet-store-web
    networks:
      - backend
    ports:
      - :3000
  db:
    build: database
    image: corentingarreau/pet-store-db
    networks:
      - backend
    volumes:
      - pets-data:/var/lib/postgresql/data

networks:
  backend:


volumes:
  pets-data:
